-- Active: 1762279716247@@127.0.0.1@3306@agentura
CREATE SCHEMA IF NOT EXISTS agentura
DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci;

CREATE TABLE IF NOT EXISTS modelka(
    id INT AUTO_INCREMENT PRIMARY KEY,
    jmeno VARCHAR(30) NOT NULL,
    prijmeni VARCHAR(50) NOT NULL,
    vyska DECIMAL(10,2) NOT NULL,
    
)